### login
POST http://localhost:8081/api/v2/login HTTP/1.1
Content-Type: application/json

{"username": "admin", "password": "1234"}


### register
POST http://localhost:8081/api/v2/register HTTP/1.1
Content-Type: application/json

{"username": "root", "password": "1234"}

### get product
GET http://localhost:8081/api/v2/product?token=1234 HTTP/1.1
